### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by Miguelus373**
#### In this milestone we:
Added all the logic for the game: 
- Checking for a winner 
- Checking for a draw 
- Checking for an invalid move

Added the user interface:
- The terminal board
- The terminal winning, draw, and invalid move messages

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
## Changes Required! :recycle: 
Hi @Miguelus373 and @carlos-ssh! You have done a commendable job of maintaining a professional pull request and making sure that your game meets its functional requirements. However, there are some key points I'd like you to consider before moving on. These are:

- [x] The code for this project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)) __[HINT]__ There is a possibility of creating a `Player` class which could take on the responsibility of choosing the winner.
- [x] __[OPTIONAL]__ Using `require_relative` for files in your directory instead of `require` is a ruby convention. You have used `require` in the `main.rb` file for a file in your directory.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- Please remove the unnecessary `.DS_Store` file from your repository.

  image

- Divide your code into classes. Put the code where it belongs, for example, the board class should be responsible for displaying the board and not figuring out if a player wins/lose the game or if it's a draw. Put the game logic in a different class.

- Move the `is game draw?` logic from the `bin/main.rb`. Keep all the game logic in a class.

#### [OPTIONAL]

- You can write `puts '*'.red * 40` instead of `40.times { print '*'.red }`. The result will be the same.
- Use `require_relative` instead of `require` to import files from `/lib`.
- Add a `gemfile` and put all the required gems inside that.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Review by bertil291utn — CHANGES_REQUESTED** [review]
# **Status:** Changes requested 🟠 
<p align="center"> image <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish all the requirements, you required to do these changes, listed below:

- Edit pull request message following this [guideline](https://cdn.filestackcontent.com/osvFJEkQHWQsgDe0PJoQ)
- The number nine position should not be invalid
image
  - [ ] Please fix this issue

### Summary

-  Guys everything looks fine just one issue 

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

**Comment by carlos-ssh** [comment]
**Milestone 3: Game logic**

**In this milestone we:**

Added all the logic for the game:

Checking for a winner
Checking for a draw
Checking for an invalid move
Added the user interface:

The terminal board
The terminal winning, draw, and invalid move messages

**Review by expjazz — APPROVED** [review]
## Status: Project Approved :clap: 

Great work implementing all the changes previously asked. 

#### Change the gemfile name to Gemfile (needs to be capitalized, otherwise won't execute the bundle install). Also fix the conflict you have before merging.

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Pull request merged**
